### ISSUE TITLE
Module naming consistency

### ISSUE THREAD

**Issue by rwhitworth** [nemoNoboru/monkey_typing#2]
Within the README.md the module is named `monkey_type`, `MonkeyType`, and `monkeyType`.  I found this confusing when trying to install the gem and use the module in irb.  Is there a single name that can be used consistently to reduce friction for a new user of the module?

Also, congrats on the GSoC work!

**Comment by nemoNoboru** [comment]
will work on it. and thanks. 
Man, the gsoc is just awesome, I guess I was just lucky. 
If you are a student consider making a proposal.  :)

**Comment by nemoNoboru** [comment]
I've done some research and [by this naming recommendations](http://guides.rubygems.org/name-your-gem/) the names are ok.
gem name `monkey_type` -> require statement `require 'monkey_type'` -> main module `MonkeyType`
By the way, after the merge of your pull request the usage of the gem is pretty clear now (= less friction).  thanks again!
